import { MonitorSpan } from '../entities/monitor-span.entity';
import { MonitorSpanMap } from './monitor-span.map';

const id = '';
const monLocId = '';
const mpcValue = 0;
const mecValue = 0;
const maxLowRange = 0;
const spanValue = 0;
const fullScaleRange = 0;
const beginDate = new Date(Date.now());
const beginHour = 12;
const endDate = new Date(Date.now());
const endHour = 12;
const defaultHighRange = 0;
const flowSpanValue = 0;
const flowFullScaleRange = 0;
const componentTypeCd = '';
const spanScaleCd = '';
const spanMethodCd = '';
const userId = '';
const updateDate = new Date(Date.now());
const spanUomCd = '';

const entity = new MonitorSpan();
entity.id = id;
entity.monLocId = monLocId;
entity.mpcValue = mpcValue;
entity.mecValue = mecValue;
entity.maxLowRange = maxLowRange;
entity.spanValue = spanValue;
entity.fullScaleRange = fullScaleRange;
entity.beginDate = beginDate;
entity.beginHour = beginHour;
entity.endDate = endDate;
entity.endHour = endHour;
entity.defaultHighRange = defaultHighRange;
entity.flowSpanValue = flowSpanValue;
entity.flowFullScaleRange = flowFullScaleRange;
entity.componentTypeCd = componentTypeCd;
entity.spanScaleCd = spanScaleCd;
entity.spanMethodCd = spanMethodCd;
entity.userid = userId;
entity.updateDate = updateDate;
entity.spanUomCd = spanUomCd;

describe('MonitorSpanMap', () => {
  it('maps an entity to a dto', async () => {
    const map = new MonitorSpanMap();
    const result = await map.one(entity);
    expect(result.id).toEqual(id);
    expect(result.monLocId).toEqual(monLocId);
    expect(result.mpcValue).toEqual(mpcValue);
    expect(result.mecValue).toEqual(mecValue);
    expect(result.maxLowRange).toEqual(maxLowRange);
    expect(result.spanValue).toEqual(spanValue);
    expect(result.fullScaleRange).toEqual(fullScaleRange);
    expect(result.beginDate).toEqual(beginDate);
    expect(result.beginHour).toEqual(beginHour);
    expect(result.endDate).toEqual(endDate);
    expect(result.endHour).toEqual(endHour);
    expect(result.defaultHighRange).toEqual(defaultHighRange);
    expect(result.flowSpanValue).toEqual(flowSpanValue);
    expect(result.flowFullScaleRange).toEqual(flowFullScaleRange);
    expect(result.componentTypeCd).toEqual(componentTypeCd);
    expect(result.spanScaleCd).toEqual(spanScaleCd);
    expect(result.spanMethodCd).toEqual(spanMethodCd);
    expect(result.userid).toEqual(userId);
    expect(result.updateDate).toEqual(updateDate);
    expect(result.spanUomCd).toEqual(spanUomCd);
    expect(result.active).toEqual(false);
  });
});
